### ISSUE TITLE
Set iframe src for describo app

### ISSUE THREAD

**Issue by marcolarosa** [Sciebo-RDS/oc-describo#5]
When I load the describo app inside owncloud, and in the mode where i use the describo controls to talk to owncloud, I see a CSP error about iframe-src.

![Screen Shot 2021-07-23 at 9 27 38 am](https://user-images.githubusercontent.com/2639995/126721228-a23eab76-fe9e-4bd9-89e4-d56ccd1ff1a1.png)

I found // https://gist.github.com/butonic/4e6d050b778866e3aa99af14d947461 which suggests that we should be able to set the iframe src in the csp so this would work.

I tired adding:
```
$policy = new OCP\AppFramework\Http\EmptyContentSecurityPolicy();
$policy->addAllowedFrameDomain('http://localhost:8000');

\OC::$server->getContentSecurityPolicyManager()->addDefaultPolicy($policy);
```

to lib/templates/main.research.php but it still doesn't work. Thoughts?

**Comment by marcolarosa** [comment]
I've put it in the wrong spot! When I added it to appinfo/app.php at the very top it worked.

```
$policy = new OCP\AppFramework\Http\EmptyContentSecurityPolicy();
$policy->addAllowedFrameDomain('http://localhost:8000');

\OC::$server->getContentSecurityPolicyManager()->addDefaultPolicy($policy);
// https://gist.github.com/butonic/4e6d050b778866e3aa99af14d9474613

\OC::$server->getNavigationManager()->add(function () {
    $urlGenerator = \OC::$server->getURLGenerator();

....
```

But, I've hard coded the url. It would be good to be able to specify an array of urls in the config. Is that possible?

**Comment by Heiss** [comment]
I add this policy stuff already in the [PageController](https://github.com/Sciebo-RDS/oc-describo/blob/1221577485448e3a24b0e27689d35a0875154a97/php/lib/Controller/PageController.php#L175). And it uses the uiURL in the [configuration.php](https://github.com/Sciebo-RDS/oc-describo/blob/1221577485448e3a24b0e27689d35a0875154a97/php/configuration.php#L16) to enable it for your wanted UI.

So it seems, that you want to add a new URL to the uiURL instead of only a single value. Yeah this is possible.

If you want place the policy stuff in the app.php, it enables iframe includes in all pages. In my understanding, this is not necessary, but it is also not a security risk. So we can place it there.
